"""
Django settings for meta project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import datetime, timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES = BASE_DIR / "templates"
STATIC = BASE_DIR / "static"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-ca^kp9dv!y1fk)2b28j1cdqnsz1ryhjq$e-j6+20^bck2w#b%*"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "acecrm.in",
    "www.acecrm.in",
    "doctrine-concrete-automatic.ngrok-free.dev",
]

CSRF_TRUSTED_ORIGINS = [
    "https://acecrm.in",
    "https://www.acecrm.in",
    "https://doctrine-concrete-automatic.ngrok-free.dev",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "apk"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "meta.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [TEMPLATES],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "meta.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [STATIC]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# meta all references

META_APP_ID = 1627673575362248
META_APP_SECRET = "54b380da9ae4234f3061d3583fdc9743"
META_REDIRECT_URI = (
    "https://doctrine-concrete-automatic.ngrok-free.dev/auth/meta/callback/"
)
USER_ACCESS_TOKEN = "EAAXIXElFDsgBSfskNFvW3e06tFfTZBkJD4nH4NoOcejlob7HhBi2BjY6SeTr4N757vZAw56cYf4sFIrekfyPw3VkhFXtV89J8htyJZAX7k6s5o0ZCjRQNvC3BJoYK2Bbx4arPhuUAGXbm2pwYtK37DUF1SmIvj0DH7jnmAhQP7HBrzSumXNf9YNjjdGSSv0cocMe7PytcxepxLZBMxyV5zpksUGVZC7y2iNiUuzjmLGqwQZAFgf4fSAhBrz0KmRcTRdhPHCXkCOZCLDtjKtAvCo3wZC9YtsgHcZAxZCSRBxHKjYC12zm9w5dHhioIgNvpzsZAJYmGz55MGUZD"
AD_ACCOUNT_ID = 4755523421433857
